#!/bin/bash
# GitHub Token Setup Guide

echo "GITHUB TOKEN SETUP REQUIRED"
echo "==========================="
echo ""
echo "To push Kimmy Scalper to GitHub, you need a Personal Access Token (PAT)."
echo ""
echo "Step 1: Create a GitHub token:"
echo "   https://github.com/settings/tokens/new"
echo ""
echo "Step 2: Select scopes:"
echo "   ☑️ repo (Full control of private repositories)"
echo ""
echo "Step 3: Generate token and COPY it"
echo ""
echo "Step 4: Set the token:"
echo "   export GITHUB_TOKEN='ghp_YOUR_TOKEN_HERE'"
echo ""
echo "Step 5: Then run:"
echo "   cd /root/.openclaw/workspace/KIMMY_SCALPER"
echo "   gh repo create kimmy-scalper --public --source=. --push"
echo ""
echo "OR use HTTPS:"
echo "   git remote add origin https://USERNAME:TOKEN@github.com/USERNAME/kimmy-scalper.git"
echo "   git push -u origin main"
echo ""
echo "==========================="
